version: "3.5"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2190:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - nifi-network-kaftest

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9192:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - nifi-network-kaftest
      
  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9193:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
      - kafka1
    networks:
      - nifi-network-kaftest

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    hostname: kafka-ui
    ports:
      - "8888:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka1
      - kafka2
    networks:
      - nifi-network-kaftest

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-init
    depends_on:
      - kafka1  
      - kafka2  
    command: >
      bash -c "
      echo ' Ожидаем запуск Kafka...' &&
      sleep 30 &&
      kafka-topics ----bootstrap-server kafka1:9092 --delete --topic 'test-user_blocks-changelog' --if-exists || true &&
      echo ' Создаем топик my-replicated-topic...' &&
      kafka-topics --bootstrap-server kafka1:9092 --create --topic my-replicated-topic --partitions 3 --replication-factor 2 &&
      echo ' Топик создан!'
      "
    restart: on-failure:3
    networks:
      - nifi-network-kaftest

  kafka-connect:
    image: debezium/connect:2.3
    hostname: kafka-connect
    depends_on:
      - kafka1
    environment:
      BOOTSTRAP_SERVERS: kafka1:9092
      GROUP_ID: connect-cluster
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    ports:
      - "8089:8083"
    networks:
      - nifi-network-kaftest

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    command: >
      postgres 
      -c wal_level=logical 
      -c max_wal_senders=10 
      -c max_replication_slots=10
    ports:
      - "5435:5432"
    volumes:
      - post:/./postgres-data:/var/lib/postgresql/data
      - post2:/./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nifi-network-kaftest

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_DATA: /var/lib/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    user: "472"
    networks:
      - nifi-network-kaftest

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka1
    environment:
      KAFKA_BROKERCONNECT: kafka1:9092
    ports:
      - "9003:9000"
    networks:
      - nifi-network-kaftest

  kafka-consumer2:
    image: python:3.9-slim
    container_name: kafka-consumer2
    networks:
      - nifi-network-kaftest
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092"
    volumes:
      - /home/mes-admin/kafka-producer/consumer.py:/app/consumer.py
    command: >
      bash -c "
      pip install faust kafka-python &&
      python /app/consumer.py
      "
    restart: 'no'

  kafka-connector:
    image: python:3.9-slim
    container_name: kafka-connector
    networks:
      - nifi-network-kaftest
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092"
    depends_on:
      - kafka-connect
      - kafka1
      - postgres
    volumes:
      - /home/mes-admin/kafka-producer/connector.py:/app/connector.py
    command: >
      bash -c "
      pip install --no-cache-dir kafka-python requests &&
      python /app/connector.py
      "
    restart: 'no'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - /home/mes-admin/kafka-producer/prometheus.yml:/etc/prometheus/prometheus.yml 
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - nifi-network-kaftest
    restart: unless-stopped
    depends_on:
      - kafka-connect-exporter

  kafka-connect-exporter:
    image: python:3.9-alpine  
    container_name: kafka-connect-exporter
    depends_on:
      - kafka-connect
    environment:
      KAFKA_CONNECT_URL: "http://kafka-connect:8083"
      PORT: "8084"
      SCRAPE_INTERVAL: "10"
    ports:
      - "8084:8084"
    volumes:
      - /home/mes-admin/kafka-producer/kafka-exporter:/app  # Монтируем папку с кодом
    command: >
      sh -c "
      cd /app &&
      pip install prometheus-client requests &&
      python kafka_connect_exporter.py
      "
    networks:
      - nifi-network-kaftest
    restart: 'no'

volumes:
  pip-cache:
  grafana_data:
  post:
  post2:
  prometheus-config:
  prometheus-data:

networks:
  nifi-network-kaftest:
    driver: bridge
